Gemfile, app/assets/stylesheets/spree/backend/spree_braintree_vzero.css, app/helpers/spree/admin/navigation_helper_decorator.rb, app/models/spree/braintree_checkout.rb, app/models/spree/gateway/braintree_vzero_base.rb, app/models/spree/payment_decorator.rb
Moves updating payment state to after_commit (after BraintreeCheckout state change).
Removes redundant order update.
Reloads order in payment update to prevent re-updating it with wrong data.
Display icon-settle as icon-capture.
Removes redundant CSS file.
=> Fix payments settling

app/controllers/spree/api/v1/braintree_client_token_controller.rb, config/routes.rb, spec/controllers/spree/api/v1/braintree_client_token_controller_spec.rb, spec/vcr/Spree_Api_V1_BraintreeClientTokenController/POST_create/guest_checkout/returns_proper_json_data_when_gateway_not_specified.yml, spec/vcr/Spree_Api_V1_BraintreeClientTokenController/POST_create/guest_checkout/returns_proper_json_data_when_gateway_specified.yml, spec/vcr/Spree_Api_V1_BraintreeClientTokenController/POST_create/user_checkout/returns_proper_json_data_when_gateway_not_specified.yml, spec/vcr/Spree_Api_V1_BraintreeClientTokenController/POST_create/user_checkout/returns_proper_json_data_when_gateway_specified.yml, spec/vcr/Spree_Gateway_BraintreeVzeroBase/valid_credentials/generates_token_for_User_registered_in_Braintree.yml
This PR adds API endpoint for getting client_token from Braintree servers. It also adds routes for this action, VCR, and specs.
=> Braintree client token API endpoint

spec/models/gateway/braintree_vzero_base_spec.rb
This PR is fixing specs, where ```
def client_token(order = nil, user =
nil)
``` is getting Spree::User instance as the first argument.
=> fix specs to provide proper params for client_token method

app/controllers/spree/user_sessions_controller_decorator.rb
Not every spree project uses `spree_auth_devise`
=> We should only decorate Spree::UserSessionsController if it's defined

Gemfile
It is no longer needed with Rails 5.
=> Remove test-after-commit gem

app/models/spree/gateway/braintree_vzero_base.rb, spec/models/gateway/braintree_vzero_base_spec.rb, spec/vcr/Spree_Gateway_BraintreeVzeroBase/valid_credentials/_capture/captures_authorized_amount/updates_Payment_state.yml
When `Spree::Config.auto_capture_on_dispatch` is set to `true` and I want to ship order, `process_order_payments` method is performed on `shipment` and `capture!` is called - throws error cause it's not defined in Braintree payment gateway.
=> Add capture method to the braintree payment gateway

app/models/spree/order_decorator.rb, spec/controllers/spree/checkout_controller_spec.rb
Uses proper namespace. Fixes `NameError: uninitialized constant Core` exception.
=> Use proper namespace

Gemfile
Ruby 2.4 is supported from 2.3.1 version of webmock (tested with 2.3.1 and 3.0.1).
=> Ruby 2.4 compatibility

app/controllers/spree/api/braintree_client_token_controller.rb, config/routes.rb, spec/controllers/spree/api/braintree_client_token_controller_spec.rb, spec/vcr/Spree_Api_BraintreeClientTokenController/POST_create/guest_checkout/returns_proper_json_data_when_gateway_not_specified.yml, spec/vcr/Spree_Api_BraintreeClientTokenController/POST_create/guest_checkout/returns_proper_json_data_when_gateway_specified.yml, spec/vcr/Spree_Api_BraintreeClientTokenController/POST_create/user_checkout/returns_proper_json_data_when_gateway_not_specified.yml, spec/vcr/Spree_Api_BraintreeClientTokenController/POST_create/user_checkout/returns_proper_json_data_when_gateway_specified.yml
This is just a copy/paste job from @jafffmen work on #63. The only changes made were:
* All `v1` prefixes have been removed since that did not happen until the 3.1 version.
* Finding the active braintree gateway doesn't use the `active` scope since that wasn't added to Spree::PaymentMethod until 3.1. Instead a simple `where(active: true)` is used.
=> Backport token API to 3.0 branch

app/helpers/spree/admin/decorated_navigation_helper.rb, app/helpers/spree/admin/navigation_helper_decorator.rb, config/initializers/prepend_helpers.rb
Hello,
I’ve experienced the #80 issue when I deployed an application with this gem to production. I couldn’t figure out why is the `Spree::Admin::NavigationHelper` being loaded twice, but I’ve found a solution to the problem with `Module#prepend`.
=> Fix for SystemStackError (stack level too deep) issue in production (#80)

app/models/spree/order_decorator.rb, app/views/spree/shared/braintree_vzero/_dropin.js.erb, app/views/spree/shared/braintree_vzero/_hosted.js.erb, app/views/spree/shared/braintree_vzero/_paypal.js.erb, spec/controllers/spree/checkout_controller_spec.rb
Changed `order.total` to `order.order_total_after_store_credit` so store credit isn't ignored.
=> Fix for PayPal and dropin payment methods ignoring store_credit

app/models/braintree/successful_response_decorator.rb
Fixed bug that prevented avs_response from being saved into the database.
=> Fixed null avs_response in spree_payments table

spree_braintree_vzero.gemspec
Since Spree 4.0 [doesn't require deface](https://github.com/spree/spree/pull/9394) we need to require it here
=> Added Deface as dependency

.travis.yml
Makes Travis CI trigger `Ruby: 2.5.1 Gemfile: gemfiles/spree_3_5.gemfile` build.
=> Misspelled extension name

app/models/concerns/spree/gateway/braintree_vzero/legacy_rails_patch.rb, app/models/spree/gateway/braintree_vzero_drop_in_ui.rb, app/models/spree/gateway/braintree_vzero_hosted_fields.rb
fixes #216
Alternatively, we could provide separate dedicated gem versions, one for `Rails < 5.2 (Spree < 3.6)` and another one for `Rails >= 5.2 (Spree >= 3.6)`
=> after_save callbacks - patch for Rails < 5.2 apps

app/controllers/spree/admin/payments_controller_decorator.rb
Fix for https://github.com/spree-contrib/spree_braintree_vzero/pull/234
Included missing module which contains helper methods added in [previous](https://github.com/spree-contrib/spree_braintree_vzero/pull/234) PR, like [here](https://github.com/spree-contrib/spree_braintree_vzero/blob/841127e1528e05674a99644966357563fb0d6f2e/app/controllers/spree/checkout_controller_decorator.rb#L4) or [here](https://github.com/spree-contrib/spree_braintree_vzero/blob/841127e1528e05674a99644966357563fb0d6f2e/app/controllers/spree/orders_controller_decorator.rb#L4)
=> Add missing helpers to payments controller fix

app/assets/javascripts/spree/frontend/spree_braintree_vzero.js, app/views/spree/braintree_vzero/_paypal_checkout.html.erb, app/views/spree/checkout/payment/braintree_vzero/_three_d_secure.html.erb
This PR is fixing the `ReferenceError: Can't find variable: SpreeBraintreeVzero` issue. Also, it fixes the issue when you can't click the `Pay with PayPal` button, by waiting for the document to load first.
I am not using the `turbolinks:load` event because this event triggers multiple times in the site (because it triggers for the original document and for each cached version) and there is no easy way around it.
I was worried about `addEventListener` with the `click` because sometimes this script runes twice, but I totally forgot that the browser will not add another event with the same function and the same `capture` setting.
Closes #228
=> Fix SpreeBraintreeVzero loading issues

spree_braintree_vzero.gemspec
=> Drop whenever dependency

app/models/spree/gateway/braintree_vzero_base/utils.rb
Paying with PayPal customer expects email from it with full line items list, including discount.
This patch provides collection LineItems and pushing it altogether with other fields.
=> Add line items for paypal integration

app/models/spree/log_entry_decorator.rb
Depending on used braintree version in project,
adding new permitted classes should require changing only one simple  `#return_permitted_classes` method.
=> make permitted classes more editable for Spree::LogEntry#parsed_details
