spree-contrib/spree_braintree_vzero

app/assets/stylesheets/spree/frontend/spree_braintree_vzero.css
lib/generators/spree_braintree_vzero/install/install_generator.rb

Due to #51 css files are not added in gem.
Fixes #50

Remove css files that are not needed anymore

---

Gemfile
app/assets/stylesheets/spree/backend/spree_braintree_vzero.css
app/helpers/spree/admin/navigation_helper_decorator.rb
app/models/spree/braintree_checkout.rb
app/models/spree/gateway/braintree_vzero_base.rb
app/models/spree/payment_decorator.rb

3 0 fix payments settling

---

Gemfile
app/assets/stylesheets/spree/backend/spree_braintree_vzero.css
app/helpers/spree/admin/navigation_helper_decorator.rb
app/models/spree/braintree_checkout.rb
app/models/spree/gateway/braintree_vzero_base.rb
app/models/spree/payment_decorator.rb

3 1 fix payments settling

---

app/models/spree/braintree_checkout.rb

fixes payment_action to send correct message on failure

---

app/models/spree/braintree_checkout.rb

fixes payment_action  to send correct message on failure 3-1

---

app/models/spree/braintree_checkout.rb

fixes payment_action to send correct message on payment failure

---

app/models/braintree/successful_response_decorator.rb

fixes hash reference problem 2-2

---

app/models/braintree/successful_response_decorator.rb

fixes hash reference problem 2-3

---

app/models/braintree/successful_response_decorator.rb

fixes hash reference problem 3-1

---

app/models/braintree/successful_response_decorator.rb

fixes hash reference problem 3-0

---

app/models/braintree/successful_response_decorator.rb

fixes hash reference problem

---

.travis.yml
circle.yml
spec/spec_helper.rb

[3-1-stable] Fix CI

---

app/models/spree/gateway/braintree_vzero_base.rb

Resolves #132
Same as #135 but to 3-1 instead of master

[master] Fix setting braintree_id in address

---

app/models/spree/gateway/braintree_vzero_base/purchase_data.rb

[3-1-stable] Fix always send bill address even if identical with ship

---

app/models/spree/gateway/braintree_vzero_base/purchase_data.rb

fix(Gateway): always send bill address even if identical with ship

---

app/models/spree/gateway/braintree_vzero_base.rb
app/models/spree/gateway/braintree_vzero_base/braintree_user.rb
spec/models/gateway/braintree_vzero_base_spec.rb

Accept User model as Spree.user_class

---

app/models/spree/braintree_checkout.rb

Fix polymorphic association for some join cases - 3-1-stable

---

app/models/spree/braintree_checkout.rb

Fix polymorphic association for some join cases - 3-0-stable

---

app/models/spree/order_decorator.rb
spec/controllers/spree/checkout_controller_spec.rb

Use proper namespace

---

app/models/braintree/successful_response_decorator.rb
spec/factories/payment_factory_decorator.rb
spec/features/spree/admin/log_entries_spec.rb
spec/vcr/Log_entries/with_a_failed_log_entry/shows_a_failed_attempt.yml
spec/vcr/Log_entries/with_a_successful_log_entry/shows_a_successful_attempt.yml

Fixes #92.
Adds missing specs for log entries.

Allow braintree successful_response to receive message

---

app/models/braintree/successful_response_decorator.rb
spec/factories/payment_factory_decorator.rb
spec/features/spree/admin/log_entries_spec.rb
spec/vcr/Log_entries/with_a_failed_log_entry/shows_a_failed_attempt.yml
spec/vcr/Log_entries/with_a_successful_log_entry/shows_a_successful_attempt.yml

Allow braintree successful_response to receive message - 3-1

---

app/models/braintree/successful_response_decorator.rb
spec/factories/payment_factory_decorator.rb
spec/features/spree/admin/log_entries_spec.rb
spec/vcr/Log_entries/with_a_failed_log_entry/shows_a_failed_attempt.yml
spec/vcr/Log_entries/with_a_successful_log_entry/shows_a_successful_attempt.yml

Allow braintree successful_response to receive message - 3-0

---

app/views/spree/checkout/payment/braintree_vzero/_payment.html.erb

Added if statement to paypal button submission

---

app/assets/javascripts/spree/frontend/spree_braintree_vzero.js

This breaks integration with stripe in spree_gateway. This code shouldn't never be here in my opinion

remove handling onn braintree submit

---

app/models/spree/payment_decorator.rb

Rewrote #199 due to comments on changes

Fix problem with stack level too deep on PaymentDecorator

---

db/migrate/20160112153422_add_admin_payment_to_spree_braintree_checkout.rb
spec/support/vcr.rb
spec/vcr/Spree_Gateway_BraintreeVzeroBase/valid_credentials/_purchase/using_Vault/sends_address_data_when_address_is_new.yml

This PR fixing main issue with type name in migration reported here https://github.com/spree-contrib/spree_braintree_vzero/issues/217
Including also additional fixes:
- avoid overriding vcr cassetes
- add new one

#217 Fix: unknown type in migration  

---

app/controllers/spree/admin/payments_controller_decorator.rb
app/helpers/spree/braintree_helper.rb

Add helpers to payments controller

---

app/models/spree/gateway/braintree_vzero_drop_in_ui.rb
app/models/spree/gateway/braintree_vzero_hosted_fields.rb

I've tested it in the Rails console, and it should work fine
Closes #240

Fix autoload of LegacyRailsPatch in the dropin and hosted fields class

---

app/helpers/spree/admin/payment_methods_helper.rb

https://spark-solutions.atlassian.net/browse/SD-1139

SD-1139 Fix Misplaced Checkbox.
